name: php-cs-fixer

on:
  pull_request:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install php-cs-fixer
        run: |
          curl -sL https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer
          chmod a+x php-cs-fixer
      - name: php-cs-fixer
        run: php php-cs-fixer fix --dry-run --diff --using-cache=no
